name: flutter_localization_agent
description: "Package for in-app localization using Language Models (LLMs) to translate the base language into multiple supported languages."
version: 1.0.0
homepage: https://github.com/danedyy/Flutter-Localization-Agent
issue_tracker: https://github.com/danedyy/Flutter-Localization-Agent/issues
topics: [localization, flutter, translation]

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: English homepage
    path: screenshots/en-home.png
  - description: English dialog
    path: screenshots/en-dialog.png
  - description: English settings
    path: screenshots/en-settings.png
  - description: Arabic homepage
    path: screenshots/ar-home.png
  - description: Arabic dialog
    path: screenshots/ar-dialog.png
  - description: Arabic settings
    path: screenshots/ar-settings.png

